export const GET_LIST_PRODUCT_HOME = "GET_LIST_PRODUCT_HOME";
export const GET_LIST_PRODUCT_HOME_SUCCESS = "GET_LIST_PRODUCT_HOME_SUCCESS";
export const GET_LIST_PRODUCT_HOME_FAILED = "GET_LIST_PRODUCT_HOME_FAILED";
